// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.924
package layouts

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Test(title string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/components/layouts/Test.templ`, Line: 9, Col: 22}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</title><script src=\"/static/js/htmx-2.0.6.min.js\"></script><link rel=\"stylesheet\" href=\"/static/css/output.css\"></head><body class=\"bg-amber-300 flex flex-col h-screen\"><div class=\"navbar bg-base-100 shadow-lg\"></div><main class=\"h-full flex flex-row justify-evenly items-center\"><div class=\"bg-amber-800 p-4 m-2 rounded shadow-md flex flex-col justify-between h-1/3 w-120\"><h2 class=\"text-white font-bold mb-2\">Card Title 1</h2><div class=\"flex-grow overflow-scroll flex flex-col justify-between\"><p class=\"text-amber-200 h-10\">This is some card content for Test 1.</p><p class=\"text-amber-200 h-10\">This is some card content for Test 2.</p><p class=\"text-amber-200 h-10\">This is some card content for Test 3.</p><p class=\"text-amber-200 h-10\">This is some card content for Test 4.</p></div><button class=\"mt-4 bg-amber-600 text-white py-1 px-2 rounded\">Action</button></div><div class=\"bg-amber-800 p-4 m-2 rounded shadow-md flex flex-col justify-between h-90 w-120\"><h2 class=\"text-white font-bold mb-2\">Card Title 2</h2><p class=\"text-amber-200\">This is some card content for Test 2.</p><button class=\"mt-4 bg-amber-600 text-white py-1 px-2 rounded\">Action</button></div></main><footer class=\"footer footer-center p-4 bg-base-200 text-base-content\"><div><p>HTMX Chat Demo © 2025</p></div></footer></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
