// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.924
package layouts

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Test(title string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/components/layouts/Test.templ`, Line: 9, Col: 22}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</title><script src=\"/static/js/htmx-2.0.6.min.js\"></script><link rel=\"stylesheet\" href=\"/static/css/output.css\"><script src=\"/static/js/websocket.js\"></script></head><body class=\"flex flex-col h-screen bg-base-200\"><div class=\"navbar bg-base-100 shadow-lg\"><div class=\"flex-1\"><a class=\"btn btn-ghost text-xl\">DaisyUI Test</a></div></div><main class=\"h-full flex flex-row justify-evenly items-center\"><div class=\"card bg-base-100 shadow-xl w-96 h-[200px] overflow-hidden\"><div class=\"card-body flex flex-col p-4 h-full\"><h2 class=\"card-title\">Card Title 1</h2><div class=\"flex-1 min-h-0 overflow-y-auto\"><div class=\"space-y-2\"><p class=\"py-2\">This is some card content for Test 1.</p><p class=\"py-2\">This is some card content for Test 2.</p><p class=\"py-2\">This is some card content for Test 3.</p><p class=\"py-2\">This is some card content for Test 4.</p><p class=\"py-2\">This is some card content for Test 5.</p><p class=\"py-2\">This is some card content for Test 6.</p></div></div><div class=\"card-actions justify-end\"><button class=\"btn btn-primary\">Action</button></div></div></div><div class=\"card bg-base-100 shadow-xl w-96\"><div class=\"card-body\"><h2 class=\"card-title\">Card Title 2</h2><p>This is some card content for Test 2.</p><div class=\"card-actions justify-end\"><button class=\"btn btn-primary\">Action</button></div></div></div></main><footer class=\"footer footer-center p-4 bg-base-200 text-base-content\"><div><p>HTMX Chat Demo © 2025</p></div></footer></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
